<option value="0" {$vinculo[0]} >Nenhum</option>
<option value="1" {$vinculo[1]} >Empregado (CLT)</option>
<option value="2" {$vinculo[2]} >Diretoria</option>
<option value="3" {$vinculo[3]} >Prazo Determinado - Lei 9.601/98</option>
<option value="4" {$vinculo[4]} >Autônomo</option>
<option value="5" {$vinculo[5]} >Menor Aprendiz GAFOR</option>
<option value="6" {$vinculo[6]} >Pessoa Jurídica</option>
<option value="7" {$vinculo[7]} >Tarefeiro</option>
<option value="8" {$vinculo[8]} >Rurícola</option>
<option value="9" {$vinculo[9]} >Estagiário - GAFO</option>
<option value="10" {$vinculo[10]} >Pensionista</option>
<option value="11" {$vinculo[11]} >Funcionário Público</option>
<option value="12" {$vinculo[12]} >Terceirizado</option>
<option value="13" {$vinculo[13]} >Trabalhador Avulso</option>
<option value="14" {$vinculo[14]} >Trabalhador Não Vinculado ao RGPS, Mas com FGTS</option>
<option value="15" {$vinculo[15]} >Diretor Não Empregado com FGTS (Lei 8.036/90)</option>
<option value="16" {$vinculo[16]} >Empregado Doméstico</option>
<option value="17" {$vinculo[17]} >Autônomo Contr S/Remuner / Cooperativa de Produção</option>
<option value="18" {$vinculo[18]} >Transp Aut Contr S/Remun / Cooperativa Trabalho</option>
<option value="19" {$vinculo[19]} >Transp Autônomo Contribuição S/Salário-Base</option>
<option value="20" {$vinculo[20]} >Transportador Cooperado Cooperativa de Trabalho</option>
<option value="21" {$vinculo[21]} >Tempo Parcial - Prazo Indeterminado</option>
<option value="22" {$vinculo[22]} >Médico Residente</option>
<option value="23" {$vinculo[23]} >Aprendiz - OUTROS</option>
<option value="24" {$vinculo[24]} >Tempo Indeterminado</option>
<option value="25" {$vinculo[25]} >Programa Nacional de Estagiários</option>
<option value="26" {$vinculo[26]} >Trabalho de Temporada</option>
<option value="27" {$vinculo[27]} >Trabalho Eventual</option>
<option value="28" {$vinculo[28]} >Trabalhador Agrário - Lei 24.248</option>
<option value="29" {$vinculo[29]} >Trabalhador da Construção - Lei 22.250</option>
<option value="30" {$vinculo[30]} >Transp Coop Pr Serv Ent Ben Isenta Cota Patronal</option>
<option value="31" {$vinculo[31]} >Transp Autônomo Prod Rural PF / Missão Diplomática</option>
<option value="32" {$vinculo[32]} >Coop que Presta Serv a Empr Contrat da Coop Trab</option>
<option value="33" {$vinculo[33]} >Coop que Pr Serv a Ent Ben Isenta Cota Patronal</option>
<option value="34" {$vinculo[34]} >Agente Político</option>
<option value="35" {$vinculo[35]} >Serv Público Cargo em Comissão / Cargo Temporário</option>
<option value="36" {$vinculo[36]} >Serv Públ Cargo Efet, Magistrado, Min Públ/Tr Cont</option>
<option value="37" {$vinculo[37]} >Contr Indiv Missão Diplomática ou Dirig Sindical</option>
<option value="38" {$vinculo[38]} >Empregada(o) Doméstica(o)</option>
<option value="39" {$vinculo[39]} >Celetista</option>
<option value="40" {$vinculo[40]} >Diretor sem Vínculo Empregatício</option>
<option value="41" {$vinculo[41]} >Prazo Determinado Lei 9.601/98</option>
<option value="42" {$vinculo[42]} >Autônomo</option>
<option value="43" {$vinculo[43]} >Contrato de Aprendizagem</option>
<option value="44" {$vinculo[44]} >Funcionário Público</option>
<option value="45" {$vinculo[45]} >Tarefeiro</option>
<option value="46" {$vinculo[46]} >Rurícola</option>
<option value="47" {$vinculo[47]} >Estagiário - OUTROS</option>
<option value="48" {$vinculo[48]} >Expatriado</option>
<option value="49" {$vinculo[49]} >Pensionista</option>
<option value="50" {$vinculo[50]} >Brandina</option>
<option value="51" {$vinculo[51]} >Temporários</option>
<option value="52" {$vinculo[52]} >Expatriado - Cód. Rec. Diferenciado 0473</option>
<option value="53" {$vinculo[53]} >Estatutário</option>
<option value="54" {$vinculo[54]} >Autônomo Motorista</option>
<option value="55" {$vinculo[55]} >Agregados SPOT</option>
<option value="56" {$vinculo[56]} >Trabalho Intermitente</option>
<option value="57" {$vinculo[57]} >Prestador de Serviço Autônomo -categoria 13</option>
