<option value="0" {$salario_cont[0]} >Nenhuma</option>
<option value="1" {$salario_cont[1]} >Salário Mensal</option>
<option value="2" {$salario_cont[2]} >Salário Quinzenal</option>
<option value="3" {$salario_cont[3]} >Salário Semanal</option>
<option value="4" {$salario_cont[4]} >Salário Diário</option>
<option value="5" {$salario_cont[5]} >Salário-Hora</option>
<option value="6" {$salario_cont[6]} >Salário Tarefa</option>
<option value="7" {$salario_cont[7]} >Estagiário (Desativado)</option>
<option value="8" {$salario_cont[8]} >Salário Comissionado</option>
<option value="9" {$salario_cont[9]} >Pensionistas (Desativado)</option>
<option value="10" {$salario_cont[10]} >Expatriado (Desativado)</option>
<option value="11" {$salario_cont[11]} >Salário Comissionado Misto</option>
<option value="12" {$salario_cont[12]} >Representante (Desativado)</option>
<option value="13" {$salario_cont[13]} >Salário Decenal</option>
<option value="14" {$salario_cont[14]} >Salário Comissionado Externo</option>
<option value="15" {$salario_cont[15]} >Autônomo (Desativado)</option>
<option value="16" {$salario_cont[16]} >Pessoa Jurídica (Desativado)</option>
<option value="17" {$salario_cont[17]} >Salário Quatorzenal</option>
<option value="18" {$salario_cont[18]} >Comissionado (Desativado)</option>
<option value="19" {$salario_cont[19]} >Salário Bimestral</option>
<option value="20" {$salario_cont[20]} >Salário Inexistente</option>
<option value="21" {$salario_cont[21]} >Salário Anual</option>
<option value="22" {$salario_cont[22]} >Salário Trimestral</option>
<option value="23" {$salario_cont[23]} >Comissionado Externo (Desat)</option>
<option value="24" {$salario_cont[24]} >Salário Quadrimestral</option>
<option value="25" {$salario_cont[25]} >Salário Semestral</option>
<option value="26" {$salario_cont[26]} >Trimensalista</option>
<option value="27" {$salario_cont[27]} >Contrato Semestral</option>
<option value="28" {$salario_cont[28]} >Contrato Anual</option>
<option value="29" {$salario_cont[29]} >Diarista</option>
<option value="30" {$salario_cont[30]} >Mensalista</option>
<option value="31" {$salario_cont[31]} >Mensalista</option>
<option value="32" {$salario_cont[32]} >Mensalista</option>
<option value="33" {$salario_cont[33]} >Mensalista</option>
<option value="35" {$salario_cont[35]} >Sem Salário Fixo</option>
