<option value="0"  {$estado[0]}>Nenhum</option>
<option value="1"  {$estado[1]}>Acre - AC</option>
<option value="2"  {$estado[2]}>Alagoas - AL</option>
<option value="3"  {$estado[3]}>Amazonas - AM</option>
<option value="4"  {$estado[4]}>Amapá - AP</option>
<option value="5"  {$estado[5]}>Bahia - BA</option>
<option value="6"  {$estado[6]}>Ceará - CE</option>
<option value="7"  {$estado[7]}>Distrito Federal - DF</option>
<option value="8"  {$estado[8]}>Espírito Santo - ES</option>
<option value="9"  {$estado[9]}>Goiás - GO</option>
<option value="10"  {$estado[10]}>Maranhão - MA</option>
<option value="11"  {$estado[11]}>Minas Gerais - MG</option>
<option value="12"  {$estado[12]}>Mato Grosso do Sul - MS</option>
<option value="13"  {$estado[13]}>Mato Grosso - MT</option>
<option value="14"  {$estado[14]}>Pará - PA</option>
<option value="15"  {$estado[15]}>Paraíba - PB</option>
<option value="16"  {$estado[16]}>Pernambuco - PE</option>
<option value="17"  {$estado[17]}>Piauí - PI</option>
<option value="18"  {$estado[18]}>Paraná - PR</option>
<option value="19"  {$estado[19]}>Rio de Janeiro - RJ</option>
<option value="20"  {$estado[20]}>Rio Grande do Norte - RN</option>
<option value="21"  {$estado[21]}>Rondônia - RO</option>
<option value="22"  {$estado[22]}>Roraima - RR</option>
<option value="23"  {$estado[23]}>Rio Grande do Sul - RS</option>
<option value="24"  {$estado[24]}>Santa Catarina - SC</option>
<option value="25"  {$estado[25]}>Sergipe - SE</option>
<option value="26"  {$estado[26]}>São Paulo - SP</option>
<option value="27"  {$estado[27]}>Tocantins - TO</option>
<option value="28"  {$estado[28]}>NULL - NULL</option>