<option value="0" {$pais[0]}>Nenhuma</option>
<option value="10" {$pais[10]}>Brasileira</option>
<option value="20" {$pais[20]}>Nat Brasileiro</option>
<option value="21" {$pais[21]}>Argentina</option>
<option value="22" {$pais[22]}>Boliviana</option>
<option value="23" {$pais[23]}>Chilena</option>
<option value="24" {$pais[24]}>Paraguaia</option>
<option value="25" {$pais[25]}>Uruguaia</option>
<option value="30" {$pais[30]}>Alemã</option>
<option value="31" {$pais[31]}>Belga</option>
<option value="32" {$pais[32]}>Britânica</option>
<option value="34" {$pais[34]}>Canadense</option>
<option value="35" {$pais[35]}>Espanhola</option>
<option value="36" {$pais[36]}>Americana (EUA)</option>
<option value="37" {$pais[37]}>Francesa</option>
<option value="38" {$pais[38]}>Suíça</option>
<option value="39" {$pais[39]}>Italiana</option>
<option value="41" {$pais[41]}>Japonesa</option>
<option value="42" {$pais[42]}>Chinesa</option>
<option value="43" {$pais[43]}>Coreana</option>
<option value="45" {$pais[45]}>Portuguesa</option>
<option value="48" {$pais[48]}>Outros Latino-Am</option>
<option value="49" {$pais[49]}>Outros Asiáticos</option>
<option value="50" {$pais[50]}>Outros</option>
<option value="51" {$pais[51]}>Brasileira</option>
<option value="52" {$pais[52]}>Nat Brasileiro</option>
<option value="53" {$pais[53]}>Argentina</option>
<option value="54" {$pais[54]}>Boliviana</option>
<option value="55" {$pais[55]}>Chilena</option>
<option value="56" {$pais[56]}>Paraguaia</option>
<option value="57" {$pais[57]}>Uruguaia</option>
<option value="58" {$pais[58]}>Alemã</option>
<option value="59" {$pais[59]}>Bélgica</option>
<option value="60" {$pais[60]}>Britânica</option>
<option value="61" {$pais[61]}>Canadense</option>
<option value="62" {$pais[62]}>Espanhola</option>
<option value="63" {$pais[63]}>Norte-Americana</option>
<option value="64" {$pais[64]}>Francesa</option>
<option value="65" {$pais[65]}>Suíça</option>
<option value="66" {$pais[66]}>Italiana</option>
<option value="67" {$pais[67]}>Japonesa</option>
<option value="68" {$pais[68]}>Chinesa</option>
<option value="69" {$pais[69]}>Coreana</option>
<option value="70" {$pais[70]}>Portuguesa</option>
<option value="71" {$pais[71]}>Outr Latino-Amer</option>
<option value="72" {$pais[72]}>Outr - Asiático</option>
<option value="73" {$pais[73]}>Outros</option>
