<option value="0" {$ligacao[0]} >Nenhum</option>
<option value="1" {$ligacao[1]} >Filho(a)</option>
<option value="2" {$ligacao[2]} >Menor Criando (Adotivo)</option>
<option value="3" {$ligacao[3]} >Cônjuge</option>
<option value="4" {$ligacao[4]} >Companheiro(a)</option>
<option value="5" {$ligacao[5]} >Pai/Mãe</option>
<option value="6" {$ligacao[6]} >Sogro(a)</option>
<option value="7" {$ligacao[7]} >Irmão/Irmã</option>
<option value="8" {$ligacao[8]} >Enteado(a)</option>
<option value="9" {$ligacao[9]} >Neto(a)</option>
<option value="10" {$ligacao[10]} >Bisneto(a)</option>
<option value="11" {$ligacao[11]} >Avô(ó)</option>
<option value="12" {$ligacao[12]} >Bisavô(ó)</option>
<option value="13" {$ligacao[13]} >Amigo(a)</option>
<option value="14" {$ligacao[14]} >Cunhado(a)</option>
<option value="15" {$ligacao[15]} >Outros</option>
<option value="16" {$ligacao[16]} >Tio(a)</option>
<option value="17" {$ligacao[17]} >Sobrinho(a)</option>
<option value="18" {$ligacao[18]} >Primo(a)</option>
<option value="19" {$ligacao[19]} >Genro/Nora</option>
<option value="20" {$ligacao[20]} >Concunhado(a)</option>
<option value="21" {$ligacao[21]} >Padrasto/Madrasta</option>
<option value="22" {$ligacao[22]} >Ex-Cônjuge</option>
<option value="23" {$ligacao[23]} >Ex-Companheiro</option>
<option value="24" {$ligacao[24]} >Tutela</option>
<option value="25" {$ligacao[25]} >Curatela</option>
<option value="26" {$ligacao[26]} >Guarda Provisória</option>
