<option value="0" {$area[0]} >0 - Não Informado</option>
<option value="1" {$area[1]} >1 - Abengoa - São João da Boa Vista- Administrativo</option>
<option value="2" {$area[2]} >2 - Abengoa - São João da Boa Vista- Manutenção</option>
<option value="3" {$area[3]} >3 - Abengoa - São João da Boa Vista- Operações</option>
<option value="4" {$area[4]} >4 - Abengoa - São João da Boa Vista- Manutenção</option>
<option value="5" {$area[5]} >5 - Abengoa - São João da Boa Vista- Operações- Motoristas</option>
<option value="6" {$area[6]} >6 - Abengoa - São João da Boa Vista- Recursos Humanos - Consultoria de RH</option>
<option value="7" {$area[7]} >7 - Abengoa - São João da Boa Vista- Recursos Humanos - SSMAQ</option>
<option value="8" {$area[8]} >8 - Air Liquide - Paulínia - Administrativo</option>
<option value="9" {$area[9]} >9 - Air Liquide - Paulínia - Administrativo - PNE</option>
<option value="10" {$area[10]} >10 - Air Liquide - Paulínia - Operações</option>
<option value="11" {$area[11]} >11 - Air Liquide - Paulínia - Operações - Motoristas</option>
<option value="12" {$area[12]} >12 - Air Liquide - Paulínia - Operações - PNE</option>
<option value="13" {$area[13]} >13 - Suzano Comboio - Barra do Riacho - Manutenção</option>
<option value="14" {$area[14]} >14 - Suzano Comboio - Barra do Riacho - Operações</option>
<option value="15" {$area[15]} >15 - Suzano Comboio - Barra do Riacho - Operações - Motoristas</option>
<option value="16" {$area[16]} >16 - Suzano Comboio - Barra do Riacho - Recursos Humanos - Treinamento</option>
<option value="17" {$area[17]} >17 - Suzano Insumos - Barra do Riacho - Administrativo</option>
<option value="18" {$area[18]} >18 - Suzano Insumos - Barra do Riacho - Operações</option>
<option value="19" {$area[19]} >19 - Suzano- Insumos - Barra do Riacho - Operações - Motoristas</option>
<option value="20" {$area[20]} >20 - Suzano Madeira - Barra do Riacho- Operações</option>
<option value="21" {$area[21]} >21 - Basf - Guaratinguetá- Administrativo</option>
<option value="22" {$area[22]} >22 - Basf - Guaratinguetá- Operações</option>
<option value="23" {$area[23]} >23 - Basf - Guaratinguetá- Operações - Motoristas</option>
<option value="24" {$area[24]} >24 - Carga Geral - Dedicados -  Operações</option>
<option value="25" {$area[25]} >25 - Carga Geral - Dedicados - CJ - Operações</option>
<option value="26" {$area[26]} >26 - Carga Geral - Dedicados - CJ - Operações - Motoristas</option>
<option value="27" {$area[27]} >27 - Carga Geral - Dedicados - Distribuidora - Operações</option>
<option value="28" {$area[28]} >28 - Carga Geral - Dedicados - Distribuidora - Operações - Motoristas</option>
<option value="29" {$area[29]} >29 - Kimberly - Mogi das Cruzes - Operações</option>
<option value="30" {$area[30]} >30 - Kimberly - Mogi das Cruzes - Administrativo</option>
<option value="31" {$area[31]} >31 - Carga Geral - Dedicados - Mogi-das-Cruzes - Kimberly Clark - Operações - Motoristas</option>
<option value="32" {$area[32]} >32 - Carga Geral Pool -  Operações - Motoristas</option>
<option value="33" {$area[33]} >33 - Carga Geral Pool - Administrativo</option>
<option value="34" {$area[34]} >34 - Carga Geral Pool - Administrativo - PNE</option>
<option value="35" {$area[35]} >35 - Carga Geral Pool - Camaçari -  Operações</option>
<option value="36" {$area[36]} >36 - Carga Geral Pool - Camaçari -  Operações - Motoristas</option>
<option value="37" {$area[37]} >37 - Carga Geral Pool - Camaçari-  Administrativo</option>
<option value="38" {$area[38]} >38 - Carga Geral Pool - Camaçari-  Administrativo - PNE</option>
<option value="39" {$area[39]} >39 - Carga Geral Pool - Operações</option>
<option value="40" {$area[40]} >40 - Centro Leste - Barra do Riacho - Administrativo</option>
<option value="41" {$area[41]} >41 - Centro Leste - Barra do Riacho - Administrativo - PNE</option>
<option value="42" {$area[42]} >42 - Centro Leste - Barra do Riacho - Operações</option>
<option value="43" {$area[43]} >43 - Centro Leste - Barra do Riacho - Operações - PNE</option>
<option value="44" {$area[44]} >44 - Centro Leste - Barra do Riacho - Recursos Humanos - Consultoria de RH</option>
<option value="45" {$area[45]} >45 - Centro Leste - Barra do Riacho - Recursos Humanos - SSMAQ</option>
<option value="46" {$area[46]} >46 - CNAA- Campina Verde - Administrativo</option>
<option value="47" {$area[47]} >47 - CNAA- Campina Verde - Manutenção</option>
<option value="48" {$area[48]} >48 - CNAA- Campina Verde - Operações</option>
<option value="49" {$area[49]} >49 - Raizen - Guariba - Recursos Humanos - Treinamento</option>
<option value="50" {$area[50]} >50 - CNAA- Campina Verde - Operações - Motoristas</option>
<option value="51" {$area[51]} >51 - CNAA- Campina Verde - Recursos Humanos- Consultoria de RH</option>
<option value="52" {$area[52]} >52 - CNAA- Campina Verde - Recursos Humanos- SSMAQ</option>
<option value="53" {$area[53]} >53 - Containers - Cubatão - Operações - Motoristas</option>
<option value="54" {$area[54]} >54 - Containers - Cubatão - Recursos Humanos - Treinamento</option>
<option value="55" {$area[55]} >55 - Containers- Cubatão- Administrativo</option>
<option value="56" {$area[56]} >56 - Containers- Cubatão- Comercial</option>
<option value="57" {$area[57]} >57 - Containers- Cubatão- Operações</option>
<option value="58" {$area[58]} >58 - Raizen - Guariba - Administrativo - PNE</option>
<option value="59" {$area[59]} >59 - Raizen - Guariba - Manutenção</option>
<option value="60" {$area[60]} >60 - Raizen - Guariba - Operações</option>
<option value="61" {$area[61]} >61 - Raizen - Guariba - Operações - Motoristas</option>
<option value="62" {$area[62]} >62 - Raizen - Guariba- Recursos Humanos - SSMAQ</option>
<option value="63" {$area[63]} >63 - Raizen - Guariba- Administrativo</option>
<option value="64" {$area[64]} >64 - Raizen-Guariba- Diretoria de Agrologísitca</option>
<option value="65" {$area[65]} >65 - Raizen -Guariba- Recursos Humanos - Consultoria de RH</option>
<option value="66" {$area[66]} >66 - Raizen -Guariba- Recursos Humanos- Administração de Pessoal</option>
<option value="67" {$area[67]} >67 - Evonik - Barra do Riacho - Manutenção</option>
<option value="68" {$area[68]} >68 - Evonik - Barra do Riacho - Operações</option>
<option value="69" {$area[69]} >69 - Evonik - Barra do Riacho - Operações - Motoristas</option>
<option value="70" {$area[70]} >70 - Femsa - Cosmópolis - Manutenção</option>
<option value="71" {$area[71]} >71 - Femsa - Cosmópolis - Operações</option>
<option value="72" {$area[72]} >72 - Femsa - Cosmópolis - Operações - Motoristas</option>
<option value="73" {$area[73]} >73 - Femsa - Cosmópolis - Recursos Humanos Treinamento</option>
<option value="74" {$area[74]} >74 - Femsa - Cosmópolis- Administrativo</option>
<option value="75" {$area[75]} >75 - Femsa - Cosmópolis- Admistrativo - PNE</option>
<option value="76" {$area[76]} >76 - Femsa - Cosmópolis- Operações</option>
<option value="77" {$area[77]} >77 - Femsa - Cosmópolis- Operações - Motoristas</option>
<option value="78" {$area[78]} >78 - Femsa - Cosmópolis- Recursos Humanos - SSMAQ</option>
<option value="79" {$area[79]} >79 - Femsa - Cosmópolis- Recursos Humanos- Consultoria de RH</option>
<option value="80" {$area[80]} >80 - Femsa  T2 Jundiaí - Administrativo</option>
<option value="81" {$area[81]} >81 - Femsa  T2 Jundiaí - Administrativo - PNE</option>
<option value="82" {$area[82]} >82 - Femsa  T2 Jundiaí - Manutenção</option>
<option value="83" {$area[83]} >83 - Femsa  T2 Jundiaí - Operações</option>
<option value="84" {$area[84]} >84 - Femsa  T2 Jundiaí - Operações - Motoristas</option>
<option value="85" {$area[85]} >85 - Internacional(Barueri) - Comercial</option>
<option value="86" {$area[86]} >86 - Internacional - Operações - Motoristas - Geral</option>
<option value="87" {$area[87]} >87 - Internacional - Recursos Humanos - Treinamento</option>
<option value="88" {$area[88]} >88 - Internacional (Barueri)- Recursos Humanos - SSMAQ</option>
<option value="89" {$area[89]} >89 - Internacional- Operações - Motoristas Argentina - Mercosul</option>
<option value="90" {$area[90]} >90 - Internacional- Operações - Motoristas Chile - Mercosul</option>
<option value="91" {$area[91]} >91 - Internacional- Operações - Motoristas Dedicados - Mercosul</option>
<option value="92" {$area[92]} >92 - Internacional- Operações - Motoristas Geral - Mercosul</option>
<option value="93" {$area[93]} >93 - Internacional- Operações - Motoristas Rota Sul - Mercosul</option>
<option value="94" {$area[94]} >94 - Internacional(Barueri) - Administrativo</option>
<option value="95" {$area[95]} >95 - Internacional(Barueri) - Comercial</option>
<option value="96" {$area[96]} >96 - Internacional(Barueri) - Operações</option>
<option value="97" {$area[97]} >97 - Internacional(Itajaí) - Administrativo</option>
<option value="98" {$area[98]} >98 - Internacional(Itajaí) - Operações</option>
<option value="99" {$area[99]} >99 - Internacional(Porto Alegre) - Comercial</option>
<option value="100" {$area[100]} >100 - Internacional(Porto Alegre) - Operações</option>
<option value="101" {$area[101]} >101 - Internacional(Porto Alegre) - Recursos Humanos- Administração de Pessoal</option>
<option value="102" {$area[102]} >102 - Internacional(Uruguaiana) - Administrativo</option>
<option value="103" {$area[103]} >103 - Internacional(Uruguaiana) - Manutenção</option>
<option value="104" {$area[104]} >104 - Internacional(Uruguaiana) - Operações</option>
<option value="105" {$area[105]} >105 - Internacional(Uruguaiana) - Recursos Humanos - SSMAQ</option>
<option value="106" {$area[106]} >106 - Internacional(Uruguaiana) - Recursos Humanos - Treinamento</option>
<option value="107" {$area[107]} >107 - Internacional(Uruguaiana) - Recursos Humanos- Administração de Pessoal</option>
<option value="108" {$area[108]} >108 - Linde - Cubatão - Recursos Humanos - SSMAQ</option>
<option value="109" {$area[109]} >109 - Linde- Cubatão - Administrativo</option>
<option value="110" {$area[110]} >110 - Linde- Cubatão - Administrativo - PNE</option>
<option value="111" {$area[111]} >111 - Linde- Cubatão - Operações</option>
<option value="112" {$area[112]} >112 - Linde Cubatão - Operações - Motoristas</option>
<option value="113" {$area[113]} >113 - Linde- Cubatão - Operações - PNE</option>
<option value="114" {$area[114]} >114 - INDORAMA - Ipojuca - Administrativo</option>
<option value="115" {$area[115]} >115 - INDORAMA - Ipojuca - Administrativo - PNE</option>
<option value="116" {$area[116]} >116 - INDORAMA - Ipojuca - Manutenção</option>
<option value="117" {$area[117]} >117 - INDORAMA - Ipojuca - Operações</option>
<option value="118" {$area[118]} >118 - INDORAMA- Ipojuca - Operações - Motoristas</option>
<option value="119" {$area[119]} >119 - INDORAMA- Ipojuca- Recursos Humanos - SSMAQ</option>
<option value="120" {$area[120]} >120 - Matriz(Barueri) - Auditoria Interna</option>
<option value="121" {$area[121]} >121 - Matriz(Barueri)- Contabilidade</option>
<option value="122" {$area[122]} >122 - Matriz(Barueri)- Contas a Pagar</option>
<option value="123" {$area[123]} >123 - Matriz(Barueri)- Contas a Receber</option>
<option value="124" {$area[124]} >124 - Matriz(Barueri)- Controladoria</option>
<option value="125" {$area[125]} >125 - Matriz(Barueri) Diretoria Administrativa-Financeira</option>
<option value="126" {$area[126]} >126 - Matriz(Barueri)- Diretoria Comercial</option>
<option value="127" {$area[127]} >127 - Matriz(Barueri)- Diretoria de Agrologística</option>
<option value="128" {$area[128]} >128 - Matriz(Barueri)- Diretoria de Negócios - Químicos/ Bebidas</option>
<option value="129" {$area[129]} >129 - Matriz(Barueri)- Diretoria Recursos Humanos</option>
<option value="130" {$area[130]} >130 - Matriz(Barueri)- Faturamento</option>
<option value="131" {$area[131]} >131 - Matriz(Barueri)- Financeiro - Projetos</option>
<option value="132" {$area[132]} >132 - Matriz(Barueri)- Fiscal</option>
<option value="133" {$area[133]} >133 - Matriz(Barueri)- Manutenção</option>
<option value="134" {$area[134]} >134 - Matriz(Barueri)- Recursos Humanos - Adm Predial</option>
<option value="135" {$area[135]} >135 - Matriz(Barueri)- Recursos Humanos - Administração de Pessoal</option>
<option value="136" {$area[136]} >136 - Matriz(Barueri)- Recursos Humanos - Comunicação Interna & Marketing</option>
<option value="137" {$area[137]} >137 - Matriz(Barueri)- Recursos Humanos - SSMAQ</option>
<option value="138" {$area[138]} >138 - Matriz(Barueri)- Recursos Humanos- Treinamento</option>
<option value="139" {$area[139]} >139 - Matriz(Barueri)- Recursos Humanos- Consultoria de RH</option>
<option value="140" {$area[140]} >140 - Matriz(Barueri)- Recursos Humanos- Remuneração</option>
<option value="141" {$area[141]} >141 - Matriz(Barueri)- Suprimentos</option>
<option value="142" {$area[142]} >142 - Matriz(Barueri)- Tesouraria</option>
<option value="143" {$area[143]} >143 - Matriz(Barueri)- TI - Sistemas</option>
<option value="144" {$area[144]} >144 - Matriz(Barueri)- TI- Suporte</option>
<option value="145" {$area[145]} >145 - Matriz(Barueri)-Diretoria</option>
<option value="146" {$area[146]} >146 - Matriz(Barueri)-Diretoria de Agrologística</option>
<option value="147" {$area[147]} >147 - Matriz(Vila Olímpia)- Conselho de Administração</option>
<option value="148" {$area[148]} >148 - Matriz(Vila Olímpia)- Jurídico</option>
<option value="149" {$area[149]} >149 - Norte- Nordeste- Centro Leste - Diretoria de Negócios</option>
<option value="150" {$area[150]} >150 - Químicos - Bebidas - Mogi-Guaçu- Administrativo</option>
<option value="151" {$area[151]} >151 - Químicos - Bebidas - Mogi-Guaçu- Administrativo - PNE</option>
<option value="152" {$area[152]} >152 - Químicos - Bebidas - Mogi-Guaçu- Manutenção</option>
<option value="153" {$area[153]} >153 - Químicos - Bebidas - Mogi-Guaçu- Operações</option>
<option value="154" {$area[154]} >154 - Químicos - Bebidas - Mogi-Guaçu- Operações - Motoristas</option>
<option value="155" {$area[155]} >155 - Químicos - Betim - Administrativo</option>
<option value="156" {$area[156]} >156 - Químicos - Betim - Operações</option>
<option value="157" {$area[157]} >157 - Químicos - Betim - Operações - Motoristas</option>
<option value="158" {$area[158]} >158 - Químicos - Brasília - Operações</option>
<option value="159" {$area[159]} >159 - Químicos - Brasília - Operações - Motoristas</option>
<option value="160" {$area[160]} >160 - Químicos - Brasília - Operações - Motoristas</option>
<option value="161" {$area[161]} >161 - Químicos - Goiânia - Operações - Motoristas</option>
<option value="162" {$area[162]} >162 - Químicos - Uberlândia - Operações - Motoristas</option>
<option value="163" {$area[163]} >163 - Químicos / Bebidas - Paulínia- Recursos Humanos - SSMAQ</option>
<option value="164" {$area[164]} >164 - Químicos Cubatão - Administrativo</option>
<option value="165" {$area[165]} >165 - Químicos Cubatão - Manutenção</option>
<option value="166" {$area[166]} >166 - Químicos Cubatão - Operações - Motoristas</option>
<option value="167" {$area[167]} >167 - Químicos Cubatão - Operações</option>
<option value="168" {$area[168]} >168 - Químicos/ Bebidas - Mogi-Guaçu- Recursos Humanos - SSMAQ</option>
<option value="169" {$area[169]} >169 - Químicos/ Bebidas- Mogi-Guaçu - Operações - Motoristas</option>
<option value="170" {$area[170]} >170 - Químicos/Bebidas - Manutenção</option>
<option value="171" {$area[171]} >171 - Schincariol - Camaçari- Operações - Motoristas</option>
<option value="172" {$area[172]} >172 - Schincariol - Itú- Administrativo</option>
<option value="173" {$area[173]} >173 - Schincariol - Itú- Administrativo - PNE</option>
<option value="174" {$area[174]} >174 - Schincariol - Itú- Operações</option>
<option value="175" {$area[175]} >175 - Schincariol - Itú- Operações - Motoristas</option>
<option value="176" {$area[176]} >176 - Schincariol - Itú- Recursos Humanos - Treinamento</option>
<option value="177" {$area[177]} >177 - Schincariol -Alagoinhas- Administrativo</option>
<option value="178" {$area[178]} >178 - Schincariol -Alagoinhas- Administrativo - PNE</option>
<option value="179" {$area[179]} >179 - Schincariol -Alagoinhas- Manutenção</option>
<option value="180" {$area[180]} >180 - Schincariol -Alagoinhas- Operações</option>
<option value="181" {$area[181]} >181 - Schincariol -Alagoinhas- Operações - Motoristas</option>
<option value="182" {$area[182]} >182 - Schincariol -Alagoinhas- Recursos Humanos - Treinamento</option>
<option value="183" {$area[183]} >183 - Schincariol -Cachoeiras de Macacu- Administrativo</option>
<option value="184" {$area[184]} >184 - Schincariol -Cachoeiras de Macacu- Operações</option>
<option value="185" {$area[185]} >185 - Schincariol -Cachoeiras de Macacu- Operações - Motoristas</option>
<option value="186" {$area[186]} >186 - Schincariol -Cachoeiras de Macacu- Recursos Humanos - Treinamento</option>
<option value="187" {$area[187]} >187 - Suzano - Administrativo</option>
<option value="188" {$area[188]} >188 - Suzano - Operações</option>
<option value="189" {$area[189]} >189 - Suzano - Operações - Motoristas</option>
<option value="190" {$area[190]} >190 - Suzano Mucuri - Administrativo</option>
<option value="191" {$area[191]} >191 - Suzano Mucuri - Operações - Motoristas</option>
<option value="192" {$area[192]} >192 - Vale - Açailândia - Administrativo</option>
<option value="193" {$area[193]} >193 - Vale - Açailândia - Administrativo - PNE</option>
<option value="194" {$area[194]} >194 - Vale - Açailândia - Operações</option>
<option value="195" {$area[195]} >195 - Vale - Açailândia - Operações - Motoristas</option>
<option value="196" {$area[196]} >196 - Vale - Açailândia - Recursos Humanos - SSMAQ</option>
<option value="197" {$area[197]} >197 - Vale - Açailândia - Recursos Humanos - Treinamento</option>
<option value="198" {$area[198]} >198 - Vale - Pará - Administrativo</option>
<option value="199" {$area[199]} >199 - Vale - Pará - Operações</option>
<option value="200" {$area[200]} >200 - Vale - Pará - Operações - Motoristas</option>
<option value="201" {$area[201]} >201 - Químicos - Betim - Administrativo - PNE</option>
<option value="202" {$area[202]} >202 - Evonik - Barra do Riacho- Administrativo</option>
<option value="203" {$area[203]} >203 - Químicos - Cubatão- Recursos Humanos - SSMAQ</option>
<option value="204" {$area[204]} >204 - Shell - Paulínia - Operações - Motorista</option>
<option value="205" {$area[205]} >205 - Pullman - Raposo / Campinas- Operações</option>
<option value="206" {$area[206]} >206 - Shell - Paulínia - Operações</option>
<option value="207" {$area[207]} >207 - Shell - Paulínia - Administrativo</option>
<option value="208" {$area[208]} >208 - Pullman - Raposo / Campinas - Operações - Motorista</option>
<option value="209" {$area[209]} >209 - Suzano - Madeira - Barra do Riacho- Operações - Motorista</option>
<option value="210" {$area[210]} >210 - Evonik - Barra do Riacho - Recursos Humanos - Treinamento</option>
<option value="211" {$area[211]} >211 - Linde - Cubatão - Manutenção</option>
<option value="212" {$area[212]} >212 - Pensionistas</option>
<option value="213" {$area[213]} >213 - Suzano Madeira - Barra do Riacho - Administrativo</option>
<option value="214" {$area[214]} >214 - Suzano Madeira - Mucuri - Administrativo</option>
<option value="215" {$area[215]} >215 - Suzano Madeira - Mucuri - Operações</option>
<option value="216" {$area[216]} >216 - Suzano Madeira - Mucuri - Operações - Motoristas</option>
<option value="217" {$area[217]} >217 - Suzano Mucuri - Administrativo - PNE</option>
<option value="218" {$area[218]} >218 - Suzano Madeira - Barra do Riacho - Manutenção</option>
<option value="219" {$area[219]} >219 - Suzano Madeira - Barra do Riacho - Operações</option>
<option value="220" {$area[220]} >220 - Suzano Madeira - Barra do Riacho - Operações - Motoristas</option>
<option value="221" {$area[221]} >221 - Suzano Madeira - Barra do Riacho - Administrativo</option>
<option value="222" {$area[222]} >222 - Suzano Madeira - Barra do Riacho - Administrativo - PNE</option>
<option value="223" {$area[223]} >223 - Suzano Madeira - Mucuri - Administrativo</option>
<option value="224" {$area[224]} >224 - Suzano Madeira - Mucuri - Operações - Motoristas</option>
<option value="225" {$area[225]} >225 - Internacional(Uruguaiana) - Administração</option>
<option value="226" {$area[226]} >226 - Raizen - Guariba - Suprimentos</option>
<option value="227" {$area[227]} >227 - Suzano Madeira - Barra do Riacho - Operações</option>
<option value="228" {$area[228]} >228 - Suzano - Mucuri - Operações</option>
<option value="229" {$area[229]} >229 - Raizen - Guariba - Operações</option>
<option value="230" {$area[230]} >230 - Carga Geral - Camacari - Operacoes - PNE</option>
<option value="231" {$area[231]} >231 - Containers - Cubatão - Recursos Humanos - SSMAQ</option>
<option value="232" {$area[232]} >232 - Suzano - Mucuri - Recursos Humanos - SSMAQ</option>
<option value="233" {$area[233]} >233 - Schincariol - Cachoeira de Macacu - Administrativo - PNE</option>
<option value="234" {$area[234]} >234 - Internacional - Sao Jose Pinhais - Operacoes</option>
<option value="235" {$area[235]} >235 - Suzano Insumos - Barra do Riacho - SSMAQ</option>
<option value="236" {$area[236]} >236 - Suzano Comboio - Barra do Riacho - Administracao</option>
<option value="237" {$area[237]} >237 - Suzano - Mucuri - Manutenção</option>
<option value="238" {$area[238]} >238 - Solae - Esteio  RS - Operacoes</option>
<option value="239" {$area[239]} >239 - Solae - Esteio RS - Administrativo</option>
<option value="240" {$area[240]} >240 - Matriz(Barueri) - Projetos</option>
<option value="241" {$area[241]} >241 - Internacional - Recursos Humanos - Consultoria de RH</option>
<option value="242" {$area[242]} >242 - Sao Bernardo Campo / SP - Administração</option>
<option value="243" {$area[243]} >243 - UMOE - Sandovalina - Operações - Motoristas</option>
<option value="244" {$area[244]} >244 - UMOE - Sandovalina - Operações</option>
<option value="245" {$area[245]} >245 - UMOE - Sandovalina - Administrativo</option>
<option value="246" {$area[246]} >246 - UMOE - Sandovalina - Recursos Humanos - SSMAQ</option>
<option value="247" {$area[247]} >247 - UMOE - Sandovalina - Recursos Humanos - Consultoria RH</option>
<option value="248" {$area[248]} >248 - Matriz (Vila Olimpia) - TI Suporte</option>
<option value="249" {$area[249]} >249 - Matriz (Vila Olimpia) - Manutenção</option>
<option value="250" {$area[250]} >250 - Matriz (Vila Olimpia) - Contabilidade</option>
<option value="251" {$area[251]} >251 - Matriz (Vila Olimpia) - Recursos Humanos - Administração de Pessoal</option>
<option value="252" {$area[252]} >252 - Matriz (Vila Olimpia) - Controladoria</option>
<option value="253" {$area[253]} >253 - Matriz (Vila Olimpia) - Recursos Humanos - SSMAQ</option>
<option value="254" {$area[254]} >254 - Matriz (Vila Olimpia) - Diretoria de Operaçoes - Quimicos/Bebidas/Papeis</option>
<option value="255" {$area[255]} >255 - Matriz (Vila Olimpia) - Recursos Humanos - Consultoria de RH</option>
<option value="256" {$area[256]} >256 - Matriz (Vila Olimpia) - Recursos Humanos - Remuneração</option>
<option value="257" {$area[257]} >257 - Matriz (Vila Olimpia) - TI - Sistemas</option>
<option value="258" {$area[258]} >258 - Matriz (Vila Olimpia) - Suprimentos</option>
<option value="259" {$area[259]} >259 - Matriz (Vila Olimpia) - Recursos Humanos - Treinamento</option>
<option value="260" {$area[260]} >260 - Matriz (Vila Olimpia) - Internacional - Administrativo</option>
<option value="261" {$area[261]} >261 - Matriz (Vila Olimpia) - Tesouraria</option>
<option value="262" {$area[262]} >262 - Matriz (Vila Olimpia) - Fiscal</option>
<option value="263" {$area[263]} >263 - Matriz (Vila Olimpia) - Internacional - Operações</option>
<option value="264" {$area[264]} >264 - Matriz (Vila Olimpia) - Contas a Pagar</option>
<option value="265" {$area[265]} >265 - Matriz (Vila Olimpia) - Contas a Receber</option>
<option value="266" {$area[266]} >266 - Matriz (Vila Olimpia) - Recursos Humanos - Adm Predial</option>
<option value="267" {$area[267]} >267 - Matriz (Vila Olimpia) - Diretoria Comercial</option>
<option value="268" {$area[268]} >268 - Matriz (Vila Olimpia) - Internacional - Comercial</option>
<option value="269" {$area[269]} >269 - Matriz (Vila Olimpia) - Diretoria de Projetos</option>
<option value="270" {$area[270]} >270 - Matriz (Vila Olimpia) - Diretoria Administrativa Financeira</option>
<option value="271" {$area[271]} >271 - Matriz (Vila Olimpia) - Internacional - Recursos Humanos - SSMAQ</option>
<option value="272" {$area[272]} >272 - Cubatão - Recursos Humanos - Consultorir de RH</option>
<option value="273" {$area[273]} >273 - Cubatão - Quimicos Bebidas Papeis - Operações</option>
<option value="274" {$area[274]} >274 - CANCELADA</option>
<option value="275" {$area[275]} >275 - Matriz (Vila Olimpia) Diretoria Geral</option>
<option value="276" {$area[276]} >276 - Matriz (Vila Olimpia) Transporte de Veiculos (GTV)- Operações</option>
<option value="277" {$area[277]} >277 - Sao Bernardo Campo / SP - Operações Motoristas</option>
<option value="278" {$area[278]} >278 - Swiss Park Campinas - Comercio de Frotas</option>
<option value="279" {$area[279]} >279 - Suzano  Madeira - Muruci - Recursos Humanos - SSMAQ</option>
<option value="280" {$area[280]} >280 - Sao Bernardo Campo / SP  - Administração - PNEs</option>
<option value="281" {$area[281]} >281 - Solae - Esteio RS - Administrativio - PNEs</option>
<option value="282" {$area[282]} >282 - Total Express - Barueri - Operações</option>
<option value="283" {$area[283]} >283 - Total Express - Barueri - Operações - Motoristas</option>
<option value="284" {$area[284]} >284 - Total Express - Barueri - Administrativo</option>
<option value="285" {$area[285]} >285 - Eldorado - Três Lagoas - Operações</option>
<option value="286" {$area[286]} >286 - Eldorado - Três Lagoas - Administrativo</option>
<option value="287" {$area[287]} >287 - Eldorado - Três Lagoas - Recursos Humanos SSMAQ</option>
<option value="288" {$area[288]} >288 - Eldorado - Três Lagoas - Recursos Humanos</option>
<option value="289" {$area[289]} >289 - Eldorado - Três Lagoas - Manutenção</option>
<option value="290" {$area[290]} >290 - Eldorado - Três Lagoas - Operações - Motoristas</option>
<option value="291" {$area[291]} >291 - Containers - Cubatão - Operações</option>
<option value="292" {$area[292]} >292 - Internacional - Eldorado - Operações - Motoristas - Argentina</option>
<option value="293" {$area[293]} >293 - Internacional - Eldorado - Operações - Motoristas - Chile</option>
<option value="294" {$area[294]} >294 - Internacional - Eldorado - Operações - Motoristas - Dedicados</option>
<option value="295" {$area[295]} >295 - Internacional - Eldorado - Operações - Motoristas - Geral</option>
<option value="296" {$area[296]} >296 - Internacional - Eldorado - - Operações - Motoristas - Rota Sul</option>
<option value="297" {$area[297]} >297 - Internacional - Eldorado - Administrativo</option>
<option value="298" {$area[298]} >298 - Internacional - Eldorado - Manutenção</option>
<option value="299" {$area[299]} >299 - Internacional - Eldorado - Operações</option>
<option value="300" {$area[300]} >300 - Internacional - Eldorado - Recursos Humanos - Treinamento</option>
<option value="301" {$area[301]} >301 - Internacional - Eldorado - Comercial</option>
<option value="302" {$area[302]} >302 - Internacional - Eldorado - Recursos Humanos - Administração de Pessoal</option>
<option value="303" {$area[303]} >303 - Solae - Esteio  RS -  Recursos Humanos - SSMAQ</option>
<option value="304" {$area[304]} >304 - Sao Bernardo Campo / SP - Operacoes</option>
<option value="305" {$area[305]} >305 - QUIMICOS CONTAINERS - CUBATAO - ADMINISTRATIVO - PNE</option>
<option value="306" {$area[306]} >306 - Matriz (Vila Olímpia) - Diretoria de Negócios - Recursos Humanos SSMAQ</option>
<option value="307" {$area[307]} >307 - Raizen Combustiveis - Paulinia - Operações - Motoristas</option>
<option value="308" {$area[308]} >308 - Raízen - Jataí - Operações - Motoristas</option>
<option value="309" {$area[309]} >309 - Raizen Combustiveis - Paulinia - Operações</option>
<option value="310" {$area[310]} >310 - Suzano Madeira - Mucuri - Operações</option>
<option value="311" {$area[311]} >311 - Suzano Madeira - Mucuri - Administrativo</option>
<option value="312" {$area[312]} >312 - Raizen Combustiveis - Paulinia - Administrativo</option>
<option value="313" {$area[313]} >313 - Supergasbras - Duque de Caxias - Operações</option>
<option value="314" {$area[314]} >314 - Supergasbras - Duque de Caxias - Operações - Motoristas</option>
<option value="315" {$area[315]} >315 - Supergasbras - Duque de Caxias - Administrativo</option>
<option value="316" {$area[316]} >316 - Norte Nordeste Centro Leste e Agro - Operacoes</option>
<option value="317" {$area[317]} >317 - Suzano Madeira - Mucuri - Operações - Motoristas</option>
<option value="318" {$area[318]} >318 - Supergasbras - Duque de Caxias - Manutenção</option>
<option value="319" {$area[319]} >319 - Matriz (Vila Olimpia) - Suprimentos - Documentação</option>
<option value="320" {$area[320]} >320 - INDORAMA- Ipojuca - Recursos Humanos</option>
<option value="321" {$area[321]} >321 - NDG - Vila Olimpia - Administração</option>
<option value="322" {$area[322]} >322 - Suzano Insumos - Mucuri - Administrativo</option>
<option value="323" {$area[323]} >323 - Sao Martinho - Quirinopolis - Operações</option>
<option value="324" {$area[324]} >324 - Sao Martinho - Quirinopolis - Operações - Motoristas</option>
<option value="325" {$area[325]} >325 - Sao Martinho - Quirinopolis - Administrativo</option>
<option value="326" {$area[326]} >326 - Sao Martinho - Quirinopolis - Recursos Humanos - Treinamento</option>
<option value="327" {$area[327]} >327 - Sao Martinho - Quirinopolis - Recursos Humanos - SSMAQ</option>
<option value="328" {$area[328]} >328 - Suzano Madeira - Tres Lagoas - Operações - Motoristas</option>
<option value="329" {$area[329]} >329 - Matriz (Vila Olímpia) - Comercio de Frotas</option>
<option value="330" {$area[330]} >330 - Supergasbras - Duque de Caxias - Recursos Humanos - Treinamento</option>
<option value="331" {$area[331]} >331 - ALPEK- Ipojuca - Recursos Humanos SSMAQ</option>
<option value="332" {$area[332]} >332 - Suzano Madeira - Tres Lagoas - Recursos Humanos - SSMAQ</option>
<option value="333" {$area[333]} >333 - Matriz (Vila Olimpia) - Financeiro</option>
<option value="334" {$area[334]} >334 - Matriz (Vila Olímpia) - Internacional - Manutenção</option>
<option value="335" {$area[335]} >335 - Suzano Madeira - Três Lagoas - Administrativo</option>
<option value="336" {$area[336]} >336 - Matriz (Vila Olimpia) - Recursos Humanos - Selecao</option>
<option value="337" {$area[337]} >337 - Matriz (Vila Olimpia) - Diretoria de Operaçoes - Nordeste/Centro Leste/Agronegócio</option>
<option value="338" {$area[338]} >338 - Matriz (Vila Olimpia) Transporte de Veiculos (GTV) - Gerencia</option>
<option value="339" {$area[339]} >339 - Matriz (Vila Olimpia) Operações Dedicados - Diretoria</option>
<option value="340" {$area[340]} >340 - Matriz (Vila Olimpia) -INDORAMA Ipojuca Operacoes - Gerencia</option>
<option value="341" {$area[341]} >341 - Matriz (Vila Olimpia) - Eldorado Tres Lagoas - Gerencia</option>
<option value="342" {$area[342]} >342 - Matriz (Vila Olimpia) - Gerencia Agro</option>
<option value="343" {$area[343]} >343 - Eldorado - Três Lagoas - Manutenção</option>
<option value="344" {$area[344]} >344 - Sao Martinho - Quirinopolis - Operações</option>
<option value="345" {$area[345]} >345 - Sao Martinho - Quirinopolis - Administrativo</option>
<option value="346" {$area[346]} >346 - Suzano Madeira - Itabatan - Operações</option>
<option value="347" {$area[347]} >347 - Suzano Madeira - Itabatan - Operações</option>
<option value="348" {$area[348]} >348 - Itabatan - Administrativo</option>
<option value="349" {$area[349]} >349 - Matriz (Vila Olimpia) - Diretoria Dedicados/Agro</option>
<option value="350" {$area[350]} >350 - Matriz (Vila Olimpia) - Diretoria Não Dedicados</option>
<option value="351" {$area[351]} >351 - Matriz (Vila Olimpia) - Recursos Humanos - Comunicacao</option>
<option value="352" {$area[352]} >352 - ALPEK - Ipojuca - Administracao</option>
<option value="353" {$area[353]} >353 - Suzano Madeira - Teófilo Otoni - Operações</option>
<option value="354" {$area[354]} >354 - Suzano Madeira - Teófilo Otoni - Administrativo</option>
<option value="355" {$area[355]} >355 - Santa Adelia - Administrativo</option>
<option value="356" {$area[356]} >356 - Santa Adelia - Operações</option>
<option value="357" {$area[357]} >357 - Mercosul Uruguaiana - Motoristas</option>
<option value="358" {$area[358]} >358 - Mercosul Eldorado - Motoristas</option>
<option value="359" {$area[359]} >359 - Spot Suzano - Operações</option>
<option value="360" {$area[360]} >360 - Santa Adelia - Operações - Motoristas</option>
<option value="361" {$area[361]} >361 - Suzano Madeira - Teófilo Otoni - Operações - Motoristas</option>
<option value="362" {$area[362]} >362 - Suzano Madeira - Itabatan - Operações Motoristas</option>
<option value="364" {$area[364]} >364 - SOFTYS- Caeiras- Operações</option>
<option value="365" {$area[365]} >365 - Suzano Insumos - Tres Lagoas - Administrativo</option>
<option value="366" {$area[366]} >366 - Suzano Insumos - Tres Lagoas - Operacao</option>
<option value="367" {$area[367]} >367 - Cajamar - Operacao armazenagem</option>
<option value="368" {$area[368]} >368 - Santa Adelia Jaboticabal - Operações</option>
<option value="369" {$area[369]} >369 - Mercosul Uruguaiana - Operações</option>
<option value="370" {$area[370]} >370 - Sao Leopoldo - Operações</option>
<option value="371" {$area[371]} >371 - Ambev- Operações</option>
<option value="372" {$area[372]} >372 - Suzano Insumos - Itabatan - Operacao</option>
<option value="373" {$area[373]} >373 - Suzano Insumos - Posto da Mata - Operacao</option>
<option value="374" {$area[374]} >374 - Carga Geral - Operação - Heineken</option>
<option value="375" {$area[375]} >375 - Carga Geral - Operação - Via Varejo</option>
<option value="376" {$area[376]} >376 - Carga Geral - Operação - Mabe</option>
<option value="377" {$area[377]} >377 - INDORAMA - Ipojuca - Operações - Logística Externo</option>
<option value="378" {$area[378]} >378 - PQS - Ipojuca - Operações - Logística Externo</option>
<option value="379" {$area[379]} >379 - Carga Geral - Dedicados - CJ - Operações - Motoristas SPOT</option>
<option value="380" {$area[380]} >380 - Sao Bernardo Campo / SP - Operações Motoristas SPOT</option>
<option value="381" {$area[381]} >381 - Klabin - Administrativo</option>
<option value="382" {$area[382]} >382 - Klabin - Operações</option>
<option value="383" {$area[383]} >383 - Carga Geral Duratex- Administrativos</option>
<option value="384" {$area[384]} >384 - Carga Geral Duratex- Motoristas</option>
<option value="385" {$area[385]} >385 - Gerenc. Telemaco</option>
<option value="386" {$area[386]} >386 - Klabin - Autonomos</option>
<option value="387" {$area[387]} >387 - Suzano Areas Declivosas Operações</option>
<option value="388" {$area[388]} >388 - Internacional -Sao Leopoldo - Administrativo</option>
<option value="389" {$area[389]} >389 - Suzano Areas Declivosas Adminstrativas</option>
<option value="390" {$area[390]} >390 - Cajamar - Operacao Administrativo</option>
<option value="391" {$area[391]} >391 - Eucatex Madeira Operações</option>
<option value="392" {$area[392]} >392 - Eucatex Madeira Administrativo</option>
<option value="394" {$area[394]} >394 - Eucatex Madeira Autonomos</option>
<option value="395" {$area[395]} >395 - Internacional-Contrat. Agregados</option>
<option value="396" {$area[396]} >396 - Suzano Mad Tres Lagoas Operação</option>
<option value="397" {$area[397]} >397 - Suzano Mad Tres Lagoas Administrativo</option>
<option value="398" {$area[398]} >398 - Agua Emendada Adm</option>
<option value="399" {$area[399]} >399 - Eldorado Carregamento Operações</option>
<option value="400" {$area[400]} >400 - Agua Emendada Operaçoes</option>
<option value="401" {$area[401]} >401 - Prestadores de Serviço 13 (Esocial)</option>
<option value="402" {$area[402]} >402 - Usina Santa Vitória -Operações</option>
<option value="403" {$area[403]} >403 - Usina Santa Vitória -Adm.</option>
<option value="404" {$area[404]} >404 - Suzano Comboio - Barra do Riacho - Motoristas Sivicultura</option>
<option value="405" {$area[405]} >405 - Suzano Penta Hexa  TL-Operações</option>
<option value="406" {$area[406]} >406 - M Dias Branco Jaboatão Operações</option>
<option value="407" {$area[407]} >407 - M Dias Branco  Jaboatão Adm</option>
<option value="408" {$area[408]} >408 - M Dias Branco Jaboatão Motoristas-</option>
<option value="409" {$area[409]} >409 - BSC Madeira -adm</option>
<option value="410" {$area[410]} >410 - BSC Madeira -motoristas</option>
<option value="411" {$area[411]} >411 - BSC Madeira -oper</option>
<option value="412" {$area[412]} >412 - M Dias Branco Caruaru Motoristas-</option>
<option value="413" {$area[413]} >413 - M Dias Branco Caruaru adm</option>
<option value="414" {$area[414]} >414 - M Dias Branco Caruaru op</option>
<option value="415" {$area[415]} >415 - M Dias Branco Recife adm</option>
<option value="416" {$area[416]} >416 - M Dias Branco Recife motoristas</option>
<option value="417" {$area[417]} >417 - M Dias Branco Recife oper</option>
<option value="418" {$area[418]} >418 - M Dias Branco Salvador Oper</option>
<option value="419" {$area[419]} >419 - M Dias Branco Salvador adm</option>
<option value="420" {$area[420]} >420 - M Dias Branco Salvador motoristas</option>
<option value="421" {$area[421]} >421 - M Dias Branco Aratu Moinho motoristas</option>
<option value="422" {$area[422]} >422 - M Dias Branco Aratu Moinho oper</option>
<option value="423" {$area[423]} >423 - M Dias Branco Aratu Moinho adm</option>
<option value="999999" {$area[999999]} >999999 - Autônomos</option>
<option value="1000000" {$area[1000000]} >1000000 - Centro Leste - Barra do Riacho - Manutenção</option>
<option value="1000001" {$area[1000001]} >1000001 - Air Liquide - Paulinia - Manutenção</option>
<option value="1000002" {$area[1000002]} >1000002 - Schincariol - Itu - Manutenção</option>
<option value="1000003" {$area[1000003]} >1000003 - Schincariol - Cachoeiras do Macacu - Manutenção</option>
<option value="1000004" {$area[1000004]} >1000004 - Ambev - Jundiai - Operações</option>
<option value="1000005" {$area[1000005]} >1000005 - Ambev - Jundiai - Operações - Motoristas</option>
<option value="1000006" {$area[1000006]} >1000006 - Ambev - Jundiai - Administração</option>
<option value="1000007" {$area[1000007]} >1000007 - Ambev - Jundiai - Manutenção</option>
<option value="1000008" {$area[1000008]} >1000008 - SOFTYS- Caeiras- Motoristas</option>
<option value="1000009" {$area[1000009]} >1000009 - Melhoramentos - Caieiras - Operações</option>
<option value="1000010" {$area[1000010]} >1000010 - Melhoramentos - Caieiras - Administração</option>
<option value="1000011" {$area[1000011]} >1000011 - Internacional - Barueri - Manutenção</option>
<option value="1000012" {$area[1000012]} >1000012 - Internacional (Barueri) - Operações-Mercosul Brasill-Argentina</option>
<option value="1000013" {$area[1000013]} >1000013 - Melhoramentos - Caieiras - Administração - PNE</option>
<option value="1000014" {$area[1000014]} >1000014 - AMBEV - Jundiai - Recusos Humanos - SSMAQ</option>
<option value="1000015" {$area[1000015]} >1000015 - Schincariol - Itu - Recursos Humanos - SSMAQ</option>
<option value="1000016" {$area[1000016]} >1000016 - AMBEV - Jundiai - Recursos Humanos - Treinamento</option>
<option value="1000017" {$area[1000017]} >1000017 - Linde - Cubatao - Recursos Humanos - Consultoria</option>
<option value="1000018" {$area[1000018]} >1000018 - ALPEK - Ipojuca - Administracao</option>
<option value="1000019" {$area[1000019]} >1000019 - ALPEK-Ipojuca - Operacoes</option>
<option value="1000020" {$area[1000020]} >1000020 - ALPEK Ipojuca - Operações - Motoristas</option>
<option value="1000021" {$area[1000021]} >1000021 - Internacional - Betim - Manutenção</option>
<option value="1000022" {$area[1000022]} >1000022 - Liquigás - Ipojuca - Operações - Motoristas</option>
<option value="1000023" {$area[1000023]} >1000023 - Matriz (Vila Olimpia) - Recursos Humanos - Selecao</option>
<option value="1000024" {$area[1000024]} >1000024 - Eldorado Tres Lagoas</option>
<option value="1000025" {$area[1000025]} >1000025 - 360</option>
