<option value="0">Global/Nenhum</option>
<option value="1">Brasil</option>
<option value="411">Abu Dhabi</option>
<option value="141">Afeganistão</option>
<option value="105">África do Sul</option>
<option value="35">Aland, Ilhas</option>
<option value="303">Albânia, República da</option>
<option value="413">Alboran-Perejil, Ilhas</option>
<option value="205">Alemanha</option>
<option value="406">Alemanha, República Democrática</option>
<option value="305">Andorra</option>
<option value="95">Angola</option>
<option value="363">Anguilla</option>
<option value="36">Antártica</option>
<option value="29">Antígua e Barbuda</option>
<option value="364">Antilhas Holandesas</option>
<option value="131">Arábia Saudita</option>
<option value="62">Argélia</option>
<option value="2">Argentina</option>
<option value="310">Armênia, República da</option>
<option value="365">Aruba</option>
<option value="301">Austrália</option>
<option value="304">Áustria</option>
<option value="313">Azerbaijão, República do</option>
<option value="23">Bahamas, Ilhas</option>
<option value="317">Bahrein, Ilhas</option>
<option value="146">Bangladesh</option>
<option value="33">Barbados</option>
<option value="318">Belarus, República da</option>
<option value="213">Bélgica</option>
<option value="20">Belize</option>
<option value="76">Benin</option>
<option value="366">Bermudas</option>
<option value="6">Bolívia, Estado Plurinacional da</option>
<option value="37">Bonaire, Saint Eustatius e Saba</option>
<option value="330">Bósnia-Herzegovina, República da</option>
<option value="102">Botsuana</option>
<option value="38">Bouvet, Ilha</option>
<option value="159">Brunei</option>
<option value="212">Bulgária, República da</option>
<option value="77">Burkina Faso</option>
<option value="91">Burundi</option>
<option value="328">Butão</option>
<option value="331">Cabo Verde, República de</option>
<option value="416">Cachemira</option>
<option value="83">Camarões</option>
<option value="151">Camboja</option>
<option value="52">Canadá</option>
<option value="417">Canal, Ilhas</option>
<option value="367">Canárias, Ilhas</option>
<option value="335">Catar</option>
<option value="369">Cayman, Ilhas</option>
<option value="336">Cazaquistão, República do</option>
<option value="81">Chade</option>
<option value="5">Chile</option>
<option value="153">China, República Popular da</option>
<option value="340">Chipre</option>
<option value="341">Cingapura</option>
<option value="371">Cocos, Ilhas</option>
<option value="9">Colômbia</option>
<option value="107">Comores, Ilhas</option>
<option value="94">Congo</option>
<option value="90">Congo, República Democrática do</option>
<option value="372">Cook, Ilhas</option>
<option value="171">Coreia, República da (Norte)</option>
<option value="172">Coreia, República Popular Democrática da (Sul)</option>
<option value="80">Costa do Marfim</option>
<option value="14">Costa Rica</option>
<option value="307">Coveite (Kuwait)</option>
<option value="349">Croácia, República da</option>
<option value="22">Cuba</option>
<option value="39">Curaçao</option>
<option value="373">Delegação Especial da Palestina (Fora da Tabela 6)</option>
<option value="216">Dinamarca</option>
<option value="412">Dirce</option>
<option value="352">Djibuti</option>
<option value="30">Dominica, Ilha</option>
<option value="409">Dubai</option>
<option value="84">Egito</option>
<option value="16">El Salvador</option>
<option value="356">Emirados Árabes Unidos</option>
<option value="8">Equador</option>
<option value="358">Eritreia</option>
<option value="339">Eslovaca, República (Eslováquia)</option>
<option value="338">Eslovênia, República da</option>
<option value="202">Espanha</option>
<option value="53">Estados Unidos</option>
<option value="321">Estônia, República da</option>
<option value="86">Etiópia</option>
<option value="374">Falkland (Ilhas Malvinas)</option>
<option value="375">Feroe, Ilhas</option>
<option value="418">Fezzan</option>
<option value="359">Fiji</option>
<option value="160">Filipinas</option>
<option value="217">Finlândia</option>
<option value="161">Formosa (Taiwan)</option>
<option value="204">França</option>
<option value="415">Fretado para Brasil</option>
<option value="93">Gabão</option>
<option value="65">Gâmbia</option>
<option value="78">Gana</option>
<option value="40">Georgia do Sul e Sandwich do Sul, Ilhas</option>
<option value="355">Geórgia, República da</option>
<option value="376">Gibraltar</option>
<option value="34">Granada</option>
<option value="220">Grécia</option>
<option value="377">Groenlândia</option>
<option value="378">Guadalupe</option>
<option value="379">Guam</option>
<option value="19">Guatemala</option>
<option value="41">Guernsey</option>
<option value="11">Guiana</option>
<option value="13">Guiana Francesa</option>
<option value="68">Guiné</option>
<option value="67">Guiné-Bissau</option>
<option value="350">Guiné-Equatorial</option>
<option value="27">Haiti</option>
<option value="42">Heard e Ilhas McDonald, Ilha</option>
<option value="215">Holanda (Países Baixos)</option>
<option value="18">Honduras</option>
<option value="380">Hong Kong</option>
<option value="209">Hungria, República da</option>
<option value="132">Iêmen</option>
<option value="419">Iêmen do Sul</option>
<option value="381">Ilhas do Canal (Jersey e Guernsey)</option>
<option value="144">Índia</option>
<option value="157">Indonésia</option>
<option value="408">Inglaterra</option>
<option value="414">Interno Zona Franca de Manaus</option>
<option value="139">Irã, República Islâmica do</option>
<option value="135">Iraque</option>
<option value="206">Irlanda</option>
<option value="319">Islândia</option>
<option value="136">Israel</option>
<option value="208">Itália</option>
<option value="21">Jamaica</option>
<option value="420">Jammu</option>
<option value="154">Japão</option>
<option value="429">Jersey</option>
<option value="382">Johnston, Ilhas</option>
<option value="302">Jordânia</option>
<option value="167">Kiribati</option>
<option value="149">Laos, República Popular Democrática do</option>
<option value="383">Lebuan, Ilhas</option>
<option value="104">Lesoto</option>
<option value="311">Letônia, República da</option>
<option value="137">Líbano</option>
<option value="70">Libéria</option>
<option value="73">Líbia</option>
<option value="314">Liechtenstein</option>
<option value="316">Lituânia, República da</option>
<option value="320">Luxemburgo</option>
<option value="384">Macau</option>
<option value="329">Macedônia (Antiga República Iugoslava)</option>
<option value="106">Madagascar</option>
<option value="368">Madeira, Ilha da</option>
<option value="158">Malásia</option>
<option value="98">Malavi</option>
<option value="344">Maldivas</option>
<option value="71">Mali</option>
<option value="347">Malta</option>
<option value="385">Man, Ilha de</option>
<option value="386">Marianas do Norte</option>
<option value="61">Marrocos</option>
<option value="342">Marshall, Ilhas</option>
<option value="387">Martinica</option>
<option value="108">Maurício</option>
<option value="64">Mauritânia</option>
<option value="51">México</option>
<option value="148">Mianmar (Antiga Birmânia)</option>
<option value="163">Micronésia</option>
<option value="388">Midway, Ilhas</option>
<option value="99">Moçambique</option>
<option value="337">Moldávia, República da</option>
<option value="345">Mônaco</option>
<option value="155">Mongólia</option>
<option value="43">Montenegro</option>
<option value="389">Montserrat, Ilhas</option>
<option value="101">Namíbia</option>
<option value="370">Natal, Ilha (Navidad)</option>
<option value="165">Nauru</option>
<option value="143">Nepal</option>
<option value="15">Nicarágua</option>
<option value="74">Níger</option>
<option value="75">Nigéria</option>
<option value="390">Niue, Ilha</option>
<option value="391">Norfolk, Ilha</option>
<option value="218">Noruega</option>
<option value="392">Nova Caledônia</option>
<option value="147">Nova Zelândia</option>
<option value="134">Omã</option>
<option value="421">Pacífico, Ilhas do (Administração dos EUA)</option>
<option value="393">Pacífico, Ilhas do (Possessão dos EUA)</option>
<option value="422">Pacífico, Ilhas do (Território em Fideicomisso)</option>
<option value="322">Palau</option>
<option value="410">Palestina</option>
<option value="17">Panamá</option>
<option value="175">Papua Nova Guiné</option>
<option value="423">Papua Nova Guiné</option>
<option value="142">Paquistão</option>
<option value="3">Paraguai</option>
<option value="7">Peru</option>
<option value="394">Pitcairn, Ilha de</option>
<option value="168">Polinésia Francesa</option>
<option value="214">Polônia, República da</option>
<option value="24">Porto Rico</option>
<option value="201">Portugal</option>
<option value="88">Quênia</option>
<option value="312">Quirguiz, República da (Quirguistão)</option>
<option value="326">Reino Unido (Inglaterra)</option>
<option value="82">República Centro-Africana</option>
<option value="25">República Dominicana</option>
<option value="395">Reunião, Ilha</option>
<option value="211">Romênia</option>
<option value="97">Ruanda</option>
<option value="221">Rússia, Federação da</option>
<option value="63">Saara Ocidental</option>
<option value="176">Salomão, Ilhas</option>
<option value="169">Samoa</option>
<option value="397">Samoa Americana</option>
<option value="357">San Marino</option>
<option value="398">Santa Helena</option>
<option value="31">Santa Lúcia</option>
<option value="44">Sao Bartolomeu</option>
<option value="396">São Cristóvão e Neves</option>
<option value="28">São Cristóvão e Neves, Ilhas</option>
<option value="45">São Martinho, Ilha de (Parte Francesa)</option>
<option value="46">São Martinho, Ilha de (Parte Holandesa)</option>
<option value="399">São Pedro e Miquelão</option>
<option value="334">São Tomé e Príncipe, Ilhas</option>
<option value="32">São Vicente e Granadinas</option>
<option value="309">Seicheles</option>
<option value="66">Senegal</option>
<option value="69">Serra Leoa</option>
<option value="47">Sérvia</option>
<option value="407">Sérvia e Montenegro</option>
<option value="424">Sikkim</option>
<option value="138">Síria, República Árabe da</option>
<option value="87">Somália</option>
<option value="145">Sri Lanka</option>
<option value="103">Suazilândia</option>
<option value="85">Sudão</option>
<option value="49">Sudão do Sul</option>
<option value="219">Suécia</option>
<option value="327">Suíça</option>
<option value="12">Suriname</option>
<option value="48">Svalbard e Jan Mayen</option>
<option value="348">Tadjiquistão, República do</option>
<option value="150">Tailândia</option>
<option value="92">Tanzânia, República Unida da</option>
<option value="351">Tcheca, República</option>
<option value="426">Tchecoslováquia</option>
<option value="50">Terras Austrais Francesas</option>
<option value="400">Território Britânico no Oceano Índico</option>
<option value="425">Território da Alta Comissão do Pacífico Ocidental</option>
<option value="323">Timor Leste</option>
<option value="79">Togo</option>
<option value="178">Tonga</option>
<option value="401">Toquelau, Ilhas</option>
<option value="26">Trinidad e Tobago</option>
<option value="72">Tunísia</option>
<option value="402">Turcas e Caicos, Ilhas</option>
<option value="353">Turcomenistão, República do</option>
<option value="140">Turquia</option>
<option value="166">Tuvalu</option>
<option value="346">Ucrânia</option>
<option value="89">Uganda</option>
<option value="427">União das Repúblicas Socialistas Soviéticas</option>
<option value="4">Uruguai</option>
<option value="333">Uzbequistão, República do</option>
<option value="177">Vanuatu</option>
<option value="403">Vaticano, Estado da Cidade do</option>
<option value="10">Venezuela</option>
<option value="152">Vietnã</option>
<option value="428">Vietnã do Norte</option>
<option value="361">Virgens, Ilhas (Britânicas)</option>
<option value="362">Virgens, Ilhas (EUA)</option>
<option value="404">Wake, Ilha</option>
<option value="405">Wallis e Futuna, Ilhas</option>
<option value="96">Zâmbia</option>
<option value="100">Zimbábue</option>
<option value="54">Zona do Canal do Panamá</option>
