<option value="0" {$escolar[0]} >Nenhum</option>
<option value="1" {$escolar[1]} >Analfabeto</option>
<option value="2" {$escolar[2]} >Educação Básica Incompleta</option>
<option value="3" {$escolar[3]} >Educação Básica Completa</option>
<option value="4" {$escolar[4]} >Ensino Fundamental Incompleto</option>
<option value="5" {$escolar[5]} >Ensino Fundamental Completo</option>
<option value="6" {$escolar[6]} >Ensino Médio Incompleto</option>
<option value="7" {$escolar[7]} >Ensino Médio Completo</option>
<option value="8" {$escolar[8]} >Ensino Superior Incompleto</option>
<option value="9" {$escolar[9]} >Ensino Superior Completo</option>
<option value="10" {$escolar[10]} >Pós-Graduação</option>
<option value="11" {$escolar[11]} >Mestrado</option>
<option value="12" {$escolar[12]} >Doutorado</option>
<option value="13" {$escolar[13]} >MBA Completo</option>
<option value="14" {$escolar[14]} >PHD</option>
<option value="15" {$escolar[15]} >Pós-Graduação Incompleta</option>
<option value="16" {$escolar[16]} >Mestrado Incompleto</option>
<option value="17" {$escolar[17]} >Doutorado Incompleto</option>
<option value="18" {$escolar[18]} >Pós-Doutorado Incompleto</option>
<option value="19" {$escolar[19]} >Notório Saber</option>
<option value="20" {$escolar[20]} >MBA Incompleto</option>
<option value="21" {$escolar[21]} >Especialização Incompleta</option>
<option value="22" {$escolar[22]} >Especialização Completa</option>